Multiple messages written in the birthday channel
tolstoyevsky/hubot-happy-birthder pull request #123
Opened 2018-10-19 12:42 UTC by BehindLoader

# Please make sure all below checkboxes in the Mandatory section have been checked before submitting your PR (also don't forget to pay attention to the Depending on Circumstances section)

## Mandatory

- [ ] The commit message is an imperative and starts with a capital letter (for example, `Add something`, `Remove something`, `Fix something`, etc.).
- [ ] I made sure I hadn't put a period at the end of the the commit message(s).

## Depending on Circumstances

Some of the items in the section become mandatory if you are a first-time contributor and/or your changes are relevant to the items.

- [ ] Adding a new parameter I didn't forget to reflect it in `README.md`.
- [ ] Modifying a list of constants or imports I didn't brake an alphabetical order.
- [ ] (for first-time contributors) One of the commits in the pull request adds me to the **Acknowledgements** section in `AUTHORS.md`.

2018-10-23 08:26 UTC, polina-popova submitted a review, later dismissed

2018-10-23 09:50 UTC, eugulixes requested changes

2018-10-23 09:50 UTC, eugulixes commented on src/birthder.js
> +  const getBirthdayChannelMessage = () => {
Write a docstring for the function.

2018-10-23 09:57 UTC, polina-popova commented on src/birthder.js
> +  const getBirthdayChannelMessage = () => {
Why it is a constant and not usual function?
And complete it by a docstring.

2018-10-25 12:15 UTC, polina-popova commented on src/birthder.js
> +  let BIRTHDAY_CHANNEL_MESSAGE_INDEX = 0
Probably BIRTHDAY_CHANNEL_MESSAGE_INDEX shouldn't be in the list of constants, because it is not a constant. Let's move it to the end of the list.

2018-10-26 12:21 UTC, eugulixes commented on README.md
> +| `BIRTHDAY_CHANNEL_MESSAGE` | A "\|" separated message written in the birthday channel. | `@%username% is having a birthday soon, so let's discuss a present.` |
The description should a bit more complicated. For example,
```
The messages separated by `|` which are sent to the the birthday channel one by one.
```

2018-10-29 10:24 UTC, polina-popova commented on README.md
> +| `BIRTHDAY_CHANNEL_MESSAGE` | The messages separated by `|` which are sent to the the birthday channel one by one. | `@%username% is having a birthday soon, so let's discuss a present.` |
Let's keep the alphabetic order here.

2018-10-29 19:43 UTC, eugulixes requested changes

2018-10-29 19:43 UTC, eugulixes commented on README.md
> +| `BIRTHDAY_CHANNEL_MESSAGE` | The messages separated by `|` which are sent to the the birthday channel one by one. | `@%username% is having a birthday soon, so let's discuss a present.` |
Remove one of the redundant `the`s.

2018-10-31 13:46 UTC, polina-popova approved these changes

2018-10-31 14:31 UTC, eugulixes approved these changes

2018-10-31 14:31 UTC, merged