Choose randomly a tag from the list and only after this send a request for getting GIFs
tolstoyevsky/hubot-happy-birthder pull request #146
Opened 2018-11-28 15:12 UTC by BehindLoader

close #144 

# Please make sure all below checkboxes in the Mandatory section have been checked before submitting your PR (also don't forget to pay attention to the Depending on Circumstances section)

## Mandatory

- [ ] The commit message is an imperative and starts with a capital letter (for example, `Add something`, `Remove something`, `Fix something`, etc.).
- [ ] I made sure I hadn't put a period at the end of the the commit message(s).

## Depending on Circumstances

Some of the items in the section become mandatory if you are a first-time contributor and/or your changes are relevant to the items.

- [ ] Adding a new parameter I didn't forget to reflect it in `README.md`.
- [ ] Modifying a list of constants or imports I didn't brake an alphabetical order.
- [ ] (for first-time contributors) One of the commits in the pull request adds me to the **Acknowledgements** section in `AUTHORS.md`.

2018-11-28 21:23 UTC, eugulixes requested changes

2018-11-28 21:23 UTC, eugulixes commented on src/birthder.js
> +        const choosenTag = tags[Math.floor(Math.random() * tags.length)]
`chosenTag`

2018-11-28 21:28 UTC, eugulixes commented on src/birthder.js
> +        const tags = TENOR_SEARCH_TERM.split('+')
Let's use a comma here and change the default value for `TENOR_SEARCH_TERM`.

2018-11-29 21:51 UTC, eugulixes submitted a review, later dismissed

2018-11-30 13:20 UTC, polina-popova approved these changes

2018-11-30 13:35 UTC, merged